### ISSUE TITLE
replies to comments don't show

### ISSUE THREAD

**Issue by DominikButz** [ARKHAM-Enterprises/meteor-comments-ui#91] opened 2016-05-28 11:43 UTC
Comments can be added as expected but replies don't show. the reply shows the user and the buttons but the reply text does  not appear.  I'm using Meteor 1.3.2.4

See screenshots below

Screenshots 
![screen shot 2016-05-28 at 19 40 00](https://cloud.githubusercontent.com/assets/5699871/15627111/5af83054-250c-11e6-88f1-36f2b19e7f93.png)
![screen shot 2016-05-28 at 19 40 15](https://cloud.githubusercontent.com/assets/5699871/15627112/5b815a1e-250c-11e6-8a86-5f5a4669f183.png)

**Comment by Method-X** [comment] 2016-05-28 13:20
It doesn't work at all for me. Does it do the same thing when you set it up in a new/empty meteor app?

**Comment by DominikButz** [comment] 2016-05-29 01:58
I answered in the issue you posted.

**Comment by Method-X** [comment] 2016-05-29 04:55
<img width="717" alt="screen shot 2016-05-29 at 12 53 54 am" src="https://cloud.githubusercontent.com/assets/8339427/15631418/12e599ce-2538-11e6-90cb-24b62e8c1323.png">

**Comment by delay** [comment] 2016-06-01 01:44
I am experiencing the same trouble.  Replies do not show.  They will show if you edit the reply and then save again.  However as soon as you refresh the page they disappear again.  I am using the semantic-ui template.  
![bug_no_reply](https://cloud.githubusercontent.com/assets/638246/15695754/24c17e80-2770-11e6-8706-08e24d7a3dd0.png)

**Comment by Method-X** [comment] 2016-06-01 04:21
@delay Out of curiosity, what font are you using?

**Comment by delay** [comment] 2016-06-01 15:24
https://www.google.com/fonts/specimen/Source+Sans+Pro source sans pro. I really like it.

**Comment by delay** [comment] 2016-06-01 15:53
I did a tiny bit of testing.  replies work fine in version 0.2.15 but fail to show in the following version 1.0.0.  Which I am sure has some big changes given the versioning.  I will try to see if I can track it down further to see if I can discover the cause.

**Comment by delay** [comment] 2016-06-01 16:33
https://github.com/delay/comments-test  I made a simple project to demonstrate the bug.  The only thing that is installed is comments-ui accounts-password accounts-ui and semantic css.  if you try to make a reply it does not show.  Thanks so much for looking into this.

**Comment by m-pokrovskii** [comment] 2016-06-04 10:04
Some things. It's not updating even if i change data directly from the database.

**Comment by m-pokrovskii** [comment] 2016-06-04 13:39
Problem is here {{{enhancedContent}}}. Fast solutions is: 
1: use markdown
2: replace {{{enhancedContent}}} with {{content}}

Long solution: observing changes when using a transformed publications.

**Comment by matteodem** [comment] 2016-06-06 18:31
I was able to reproduce it, will have a look when I get to it, feel free to submit PRs if you have an idea where the problem is.

**Comment by matteodem** [comment] 2016-06-12 15:43
This is fixed in the latest version `1.1.2`

**Closed by matteodem** 2016-06-12 15:43 UTC
Labels: bug

**Comment by delay** [comment] 2016-06-12 21:38
Thanks so much for the fix!  Great work!  I love this comment package.  It has saved me a ton of time in not having to code that functionality.
